path: [/n/holylfs05/LABS/arguelles_delgado_lab/Lab/IceCube_MC/HNL/sqlite/190301/merged/merged.db, /n/holylfs05/LABS/arguelles_delgado_lab/Lab/IceCube_MC/HNL/sqlite/190302/merged/merged.db, /n/holylfs05/LABS/arguelles_delgado_lab/Lab/IceCube_MC/HNL/sqlite/190303/merged/merged.db, /n/holylfs05/LABS/arguelles_delgado_lab/Lab/IceCube_MC/HNL/sqlite/190304/merged/merged.db, /n/holylfs05/LABS/arguelles_delgado_lab/Lab/IceCube_MC/HNL/sqlite/190305/merged/merged.db, /n/holylfs05/LABS/arguelles_delgado_lab/Lab/IceCube_MC/HNL/sqlite/190306/merged/merged.db, /n/holylfs05/LABS/arguelles_delgado_lab/Lab/IceCube_MC/HNL/sqlite/190307/merged/merged.db, /n/holylfs05/LABS/arguelles_delgado_lab/Lab/IceCube_MC/HNL/sqlite/190308/merged/merged.db, /n/holylfs05/LABS/arguelles_delgado_lab/Lab/IceCube_MC/HNL/sqlite/oscNext/merged/merged.db]
graph_definition:
  arguments:
    columns: [0, 1, 2]
    detector:
      arguments: {}
      class_name: IceCube86
    dtype: torch.float32
    nb_nearest_neighbours: 8
    node_definition:
      arguments: {}
      class_name: NodesAsPulses
    input_feature_names: [dom_x, dom_y, dom_z, dom_time]
  class_name: KNNGraph
pulsemaps:
  - SRTInIcePulses
features:
  - dom_x
  - dom_y
  - dom_z
  - dom_time
truth:
  - energy
  - position_x
  - position_y
  - position_z
  - azimuth
  - zenith
  - pid
  - event_time
  - sim_type
  - interaction_type
  - elasticity
  - RunID
  - SubrunID
  - EventID
  - SubEventID
  - dbang_decay_length
  - track_length
  - stopped_muon
  - energy_track
  - energy_cascade
  - inelasticity
  - DeepCoreFilter_13
  - CascadeFilter_13
  - MuonFilter_13
  - OnlineL2Filter_17
  - L3_oscNext_bool
  - L4_oscNext_bool
  - L5_oscNext_bool
  - L6_oscNext_bool
  - L7_oscNext_bool
index_column: event_no
truth_table: truth
seed: 21
selection:
  test_noise: event_no % 5 == 0 & (pid == 1 | pid == -1)
  test_nu_e: event_no % 5 == 0 & (pid == 12 | pid == -12)
  test_nu_mu: event_no % 5 == 0 & (pid == 14| pid == -14)
  test_nu_tau: event_no % 5 == 0 & (pid == 16 | pid == -16)
  test_mu: event_no % 5 == 0 & (pid == 13 | pid == -13)

  validation_noise: event_no % 5 == 1 & (pid == 1 | pid == -1)
  validation_nu_e: event_no % 5 == 1 & (pid == 12 | pid == -12)
  validation_nu_mu: event_no % 5 == 1 & (pid == 14 | pid == -14)
  validation_nu_tau: event_no % 5 == 1 & (pid == 16 | pid == -16)
  validation_mu: event_no % 5 == 1 & (pid == 13 | pid == -13)

  train_noise: event_no % 5 > 1 & (pid == 1 | pid == -1)
  train_nu_e: event_no % 5 > 1 & (pid == 12 | pid == -12)
  train_nu_mu: event_no % 5 > 1 & (pid == 14 | pid == -14)
  train_nu_tau: event_no % 5 > 1 & (pid == 16 | pid == -16)
  train_mu: event_no % 5 > 1 & (pid == 13 | pid == -13)