_wandb:
    value:
        cli_version: 0.18.7
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": lr
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": val_loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 9
                - 53
                - 55
                - 77
                - 103
            "2":
                - 1
                - 5
                - 9
                - 53
                - 55
                - 77
                - 103
            "3":
                - 7
                - 23
                - 55
                - 66
            "4": 3.11.9
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
batch_size:
    value: 50
dataset_reference:
    value: graphnet.data.dataset.sqlite.sqlite_dataset.SQLiteDataset
early_stopping_patience:
    value: 3
fit:
    value:
        gpus: 1
        max_epochs: 50
num_workers:
    value: 10
path:
    value:
        - /n/holylfs05/LABS/arguelles_delgado_lab/Lab/IceCube_MC/HNL/sqlite2/190301/merged/merged.db
        - /n/holylfs05/LABS/arguelles_delgado_lab/Lab/IceCube_MC/HNL/sqlite2/190302/merged/merged.db
        - /n/holylfs05/LABS/arguelles_delgado_lab/Lab/IceCube_MC/HNL/sqlite2/190303/merged/merged.db
        - /n/holylfs05/LABS/arguelles_delgado_lab/Lab/IceCube_MC/HNL/sqlite2/190304/merged/merged.db
        - /n/holylfs05/LABS/arguelles_delgado_lab/Lab/IceCube_MC/HNL/sqlite2/190305/merged/merged.db
        - /n/holylfs05/LABS/arguelles_delgado_lab/Lab/IceCube_MC/HNL/sqlite2/190306/merged/merged.db
        - /n/holylfs05/LABS/arguelles_delgado_lab/Lab/IceCube_MC/HNL/sqlite2/190307/merged/merged.db
        - /n/holylfs05/LABS/arguelles_delgado_lab/Lab/IceCube_MC/HNL/sqlite2/190308/merged/merged.db
pulsemap:
    value: SRTInIcePulses
target:
    value: dbang_decay_length
